# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alone in the Tardis
email: 4afromero@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Página web dedicada a la serie de ciencia ficción Doctor Who.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://aloneinthetardis.com" # the base hostname & protocol for your site
twitter_username: reo_de_muerte
github_username:  franciscoromero23

# Build settings
markdown: kramdown
# deployment
host: 0.0.0.0
port: 5000
